<html>
<head>
    <title>Projeto2</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="css/formato.css">
</head>
<body>

    
    <h1 class="titulos">
        <p class="paragrafo">1990 - A Arpanet deixou de existir oficialmente, e a responsabilidade pelos elementos da rede de pesquisa foi passada ao NSFnet. O número de hosts já era superior aos 300 mil. A rede continuou a se espalhar entre instituições acadêmicas nos EUA e já incluía conexões às redes de pesquisa no Canadá e na Europa.Enquanto a rede conectada crescia, começou a pressão para permitir o seu uso comercial, que era proibido pela gerência de NSFnet. Em resposta à demanda foi permitida a instalação de redes paralelas para permitir o tráfego comercial. Surgiram as redes ALTERNET, a internacional PSINet, CERFNet, e NEARNet. No final de 1989, surgiu nos EUA o primeiro provedor de acesso à Internet por ligação telefônica, "The World". Em outubro de 1990 a "Clari-Net" ofereceu o primeiro recurso comercial na Internet. Em 22 de maio de 1990 a Microsoft lançou o Windows 3.0, para ser usado em microcomputadores que tinham instalado o sistema operacional MS-DOS. Era suportado pelo processador 386, podendo ser multitarefa com programas DOS e também com programas Windows.</p>
        <p class="paragrafo"> Com memória virtual e proteção, a versão 3.0 transformou os pcs em máquinas multifuncionais.A interface com o usuário foi projetada para se parecer com o "Presentation Manager": tinha um gerenciador de programas baseado em ícones e um gerenciador de arquivos em estilo árvore. Gráficos em 16 cores tornaram possível a entrega de ícones renovados. Imediatamente após o lançamento do Windows 3.0, começaram a aparecer programas para funcionar nesse ambiente, da própria Microsoft e, também, de muitos desenvolvedores.Foram vendidas cerca de 10 milhões de cópias do Windows 3.0. Timothy John Berners-Lee, com a ajuda de Robert Cailliau, em outubro de 1990, publicou uma proposta formal para a World Wide Web ( WWW ).Eles propuseram a criação de um projeto global de hipertexto, por meio da "linguagem" HTML, para permitir que pessoas, mesmo fisicamente distantes, trabalhassem juntas utilizando páginas de hipertextos, com links para qualquer tipo de arquivo: textos ou imagens e, depois, sons e vídeos.</p>
        <p class="paragrafo">Berners-Lee e Cailliau utilizaram um computador NeXTcube como o primeiro servidor Web e começaram a trabalhar na implementação de um programa editor e leitor. Era o primeiro programa navegador, denominado WorldWideWeb, baseado no Enquire. O software foi levado para outros sistemas operacionais e liberado ao público e concluído em 1991. Embora tivesse uma idéia e estrutura que também se poderia aplicar ao Gopher, que foi lançado aproximadamente na mesma época, o programa oferecia novas características:Permitia destacar palavras / frases que passavam a servir como elementos de ligação entre arquivos, os links. Assim, ao apontar essas palavras com o mouse, podia-se acessar outro documento em qualquer parte da Internet. Esse outro documento também podia oferecer novas ligações para outras informações. Ou seja, o link tornava possível a navegação pela Internet. Possibilitava a apresentação de informação com conteúdos multimidia, os hipertextos, ou seja, uma página Web podia oferecer qualquer tipo de arquivo: texto, imagens, sons e vídeos.(Mais detalhes sobre as contribuições de Bernes-Lee: aqui, aqui, aqui.).</p>
        <p class="paragrafo"> Em 19 de fevereiro de 1990 Thomas Knoll, convencido por seu irmão John, transformou sua tese de doutorado sobre processos de imagem digital em um programa que foi denominado de "ImagePro", do qual se originou o Photoshop. John Knoll acabou por oferecê-lo para a "Adobe" pois, na época, as empresas radicadas no Vale do Silício não lhe deram importância. Com o Photoshop os pcs passaram a ser verdadeiros estúdios fotográficos. A Electronic Frontier Foundation - EFF, (em português, Fundação Fronteira Eletrônica) é uma organização não-governamental sem fins lucrativos, fundada em San Francisco, Califórnia, nos Estados Unidos.Conta com representantes em Toronto, Ontário e em Washington. A organização se sustenta por doações e seu objetivo é defender as liberdades civis, a privacidade, a livre expressão, e os direitos dos consumidores no mundo digital, respeitando a Primeira Emenda da Constituição dos EUA, privilegiando a privacidade e outros valores democráticos.Foi fundada em julho de 1990 por Mitch Kapor, John Gilmore e John Perry Barlow, que haviam se conhecido por meio de uma comunidade virtual, quando o Serviço Secreto dos EUA invadiu a empresa Steve Jackson Games em uma batida policial ilegítima.</p>
        <p class="paragrafo"> Seus advogados, técnicos, e ativistas têm defendido a liberdade da expressão, a aplicação apropriada da propriedade intelectual, a privacidade e a inovação tecnológica, inclusive representando legalmente as pessoas cujos direitos e liberdades são ameaçados.A fundação também trabalha mundialmente por políticas públicas, práticas de negócio, e opções para protejam estes direitos dos consumidores. A concorrência entre os fabricantes produziu uma baixa nos preços dos computadores pessoais.A "Open Software Foundation - OSF" lançou o OSF, baseado em Mach e BSD. Em 1991 A Internet já possibilitava manipular uma variedade de aplicações (comunicação por correio eletrônico, cópia de arquivos de computadores remotos, transferência de fotografias digitalizadas e sons....), mas como era pouco amigável o seu uso era limitado, já que sendo baseada em uma série de protocolos, requeria um certo conhecimento sobre computadores e sistemas operacionais de rede, que a maioria dos usuários não tinha tempo nem interesse em obter.Paul Lindner e Mark P.</p>
        <p class="paragrafo"> McCahill da Universidade de Minnesota desenvolveram o Gopher, um protocolo de redes de computadores que foi desenhado para indexar repositórios, atuando como um mecanismo de busca de textos na Internet. Esse programa organizava as informações por assunto, e as apresentava em uma estrutura hierárquica, semelhante ao que aparece em um gerenciador, que permite ver a listagem de todos os arquivos, em um banco de dados sob menus.Assim, cada vez que se clicava sobre uma pasta o Gopher mostrava as outras pastas e/ou arquivos que estão dentro dela (ou seja, navegava para um nível mais interno na hierarquia). Quando se apontava um título de um artigo podia-se copiar esse arquivo, por meio do recurso de transferência de arquivos da Internet ( FTP ), sem ter nenhum conhecimento de códigos complexos. Portanto, qualquer usuário podia navegar de "site" em "site", procurando e podendo copiar a informação.</p><p class="paragrafo">Logo o Gopher tornou-se popular, mas tinha algumas limitações sérias, pois estava limitado apenas a arquivos de texto, não permitindo a apresentação de arquivos de imagem / som. Os menus eram muito parecidos e as ligações nos menus e documentos tinham que ser curtas (poucas palavras, no máximo) não sendo possível fazer uma ligação de um parágrafo inteiro. Ou seja, embora fosse um ótimo método de catalogação de grandes quantidades de informação textual, o Gopher não permitia apresentar a informação de uma forma mais estilística.Timothy John Berners-Lee, em 26 de fevereiro de 1991, apresentou o programa "WorldWideWeb", o primeiro navegador e editor de HTML do tipo WYSIWYG, que objetivava facilitar a consulta de documentos para pesquisas científicas. (Esse programa foi depois renomeado para Nexus, para evitar confusões com o nome World Wide Web, também criado por Berners-Lee)..O WorldWideWeb foi o primeiro programa criado que não usava só o protocolo de transferência de arquivos ( FTP ) mas também o protocolo de transferência de hipertextos (HTTP), também criado por Berners-Lee em 1989, um tipo de codificação para as páginas visualizáveis na Internet.</p>
        <p class="paragrafo"> Portanto, quando foi criado, o WorldWideWeb era a primeira e, evidentemente, a única maneira de visualizar graficamente a Internet, ou seja, iniciava-se a WWW. Resumindo, no final de 1990, Berners-Lee já havia criado as ferramentas necessárias para a WWW funcionar como a conhecemos hoje:o conceito de “link”,o navegador,o servidor e as primeiras páginas Web, que descreviam o próprio projeto, que também ficou conhecido como "World Wide Web".Tudo isso permitiu a difusão das informações e o acesso do grande público à Internet que, então, pôde se expandir. Entretanto, a novidade cresceu devagar: no final de 1992 só havia 50 "sites" Web no mundo inteiro e, um ano depois chegava a apenas 250.Assim, em 6 de agosto de 1991, Berners-Lee postou um resumo no grupo de notícias alt.hypertext, publicando a primeira página na web, colocando-a como como um serviço publicado na Internet. Assim, os conceitos de Berners-Lee se tornaram públicos, principalmente por meio do grupo de discussão WWW-talk (uma lista por e-mail iniciada em setembro de 1991).</p></h1>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/QXUpRg29iZQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <h1 class="titulos">Video da como funciona a internet</h1>
  

</body>
</html>